### ISSUE TITLE
Incorrect sha1 for long strings

### ISSUE THREAD

**Issue by nnarhinen** [hookflash/obsolete.cifre#1]
String `asdfasdfasdfasdfasdfasdfasdfasdfasdfsadfsadfsdfasdfasdfasdfasdfsf` should be converted to `c834ca59bc7ca88127749729ed71babf0b1c963a` instead I get `ca220addb9d562183722ec78b613587f5409779b`

**Comment by jugglinmike** [comment]
I can confirm. I've been working on a fix, but my crypto is sorely lacking. As far as I can tell, the error occurs for strings longer than 64 characters.

**Comment by creationix** [comment]
Added failing test case: c87af5302036cb287b2f8d63db3468ca60cef789

**Comment by creationix** [comment]
Finally found the bug.  It was missing the offset when sampling the input and just read the first 64 bytes over and over instead of the entire input.
