### ISSUE TITLE
Wrong hash values for sizes % 64 == 55

### ISSUE THREAD

**Issue by srijs** [hookflash/obsolete.cifre#2]
When testing with random data of varying sizes, Cifre produces wrong hash values for data with size % 64 == 55. This may be due to the way padding is done, but that's just a guess, really.

To reproduce, comment-in line 26 in the Rusha test file (https://github.com/srijs/rusha/blob/master/examples/test.js#L26) and run it with `node test`.

**Comment by creationix** [comment]
Thanks, it was indeed a padding bug.  Fixed in cifre version 0.0.4.
