### ISSUE TITLE
broken AES with larger data

### ISSUE THREAD

**Issue by cadorn** [hookflash/obsolete.cifre#6]
If data to be encrypted is larger than ~15 chars it can no longer be decrypted.

See test: https://github.com/openpeer/cifre/blob/master/test/aes.js

**Comment by creationix** [comment]
Strange, I have full tests for all the AES test vectors in the other test.  I wonder what's wrong here.

**Comment by creationix** [comment]
I'm not sure where the bug is.  When I merged your test case into the main AES unit test, it passed. https://github.com/openpeer/cifre/commit/41e07a43d8f15eb8e565fa7ad2d7ae271a190723

**Comment by creationix** [comment]
Ok, found the bug and I feel so dumb for not finding it sooner.  Fixed in https://github.com/openpeer/cifre/commit/5615343ec8b861c2741d25100f83baed61588bcc

**Comment by cadorn** [comment]
Thanks for the quick fix. Sorry about the typo.
